---
version: "3.8"
services:
  movies:
    image: mdinesh28/movies:latest
    ports:
      - 81:80
    deploy:
      replicas: 3
  
  train:
    image: mdinesh28/train:latest
    ports:
      - 82:80
    deploy:
      replicas: 3
    
  dth:
    image: mdinesh28/dth:latest
    ports:
      - 83:80
    deploy:
      replicas: 3
    
  recharge:
    image: mdinesh28/recharge:latest
    ports:
      - 84:80
    deploy:
      replicas: 3
   
